/* Generated By:JavaCC: Do not edit this line. CompiladorConstants.java */
package compilador.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAM = 5;
  /** RegularExpression Id. */
  int WHILE = 6;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int ELSE = 8;
  /** RegularExpression Id. */
  int CA = 9;
  /** RegularExpression Id. */
  int CF = 10;
  /** RegularExpression Id. */
  int PA = 11;
  /** RegularExpression Id. */
  int PF = 12;
  /** RegularExpression Id. */
  int PV = 13;
  /** RegularExpression Id. */
  int OP = 14;
  /** RegularExpression Id. */
  int ATTR = 15;
  /** RegularExpression Id. */
  int NUMBER = 16;
  /** RegularExpression Id. */
  int IDENTIFIER = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"program\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "<OP>",
    "\"=\"",
    "<NUMBER>",
    "<IDENTIFIER>",
  };

}
